# Generated by Django 3.2.6 on 2021-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='coordinate_x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='coordinate_y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
