# Generated by Django 3.2.6 on 2021-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210827_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinate_x',
        ),
        migrations.RemoveField(
            model_name='place',
            name='coordinate_y',
        ),
    ]
