# Generated by Django 3.2.6 on 2021-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210827_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details',
            field=models.FileField(blank=True, null=True, upload_to='places'),
        ),
    ]
