# Generated by Django 3.2.6 on 2021-08-27 22:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210828_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['serial_number']},
        ),
        migrations.AddField(
            model_name='place',
            name='my_field',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
