# Generated by Django 3.2.6 on 2021-09-08 14:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_long_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
    ]
